import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // Generated by `wrangler types`; `types:check` keeps it current.
    // drizzle-kit writes migrations/meta; formatting it would conflict with its next `db:generate`.
    ignorePatterns: ["**/worker-configuration.d.ts", "**/migrations/meta/**"],
  },
  lint: {
    ignorePatterns: ["**/worker-configuration.d.ts"],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
});
